/* General Knowledge India — 50 Questions */
const T_GK = {
  name:{en:'General Knowledge India',hi:'भारत सामान्य ज्ञान'}, icon:'🇮🇳',
  easy:[
    ["What is the capital of India?","Mumbai","Kolkata","New Delhi","Chennai",2,"New Delhi has been the capital of India since 1911."],
    ["What is the national animal of India?","Lion","Bengal Tiger","Elephant","Leopard",1,"The Bengal Tiger was declared India's national animal in 1973."],
    ["What is the national bird of India?","Eagle","Flamingo","Peacock","Parrot",2,"The Indian Peacock was declared the national bird in 1963."],
    ["What is the national flower of India?","Rose","Sunflower","Lotus","Jasmine",2,"The Lotus is India's national flower and is sacred in Hinduism and Buddhism."],
    ["How many states are there in India?","25","26","28","30",2,"India has 28 states and 8 Union Territories."],
    ["What is the longest river in India?","Yamuna","Brahmaputra","Ganga","Godavari",2,"The Ganga (Ganges) is the longest river in India at about 2,525 km."],
    ["What is the national sport of India?","Cricket","Football","Hockey","Kabaddi",2,"Field Hockey is the official national sport of India."],
    ["What is the currency of India?","Dollar","Rupee","Taka","Dinar",1,"The Indian Rupee (INR) is the official currency of India."],
    ["Which is the largest state in India by area?","Madhya Pradesh","Maharashtra","Rajasthan","Uttar Pradesh",2,"Rajasthan is the largest state in India by area."],
    ["What is the national tree of India?","Neem","Peepal","Banyan","Mango",2,"The Banyan tree is India's national tree, symbolizing longevity."],
    ["Which ocean surrounds India to the south?","Pacific Ocean","Atlantic Ocean","Indian Ocean","Arctic Ocean",2,"The Indian Ocean borders India to the south."],
    ["What is the national fruit of India?","Banana","Papaya","Mango","Guava",2,"The Mango is India's national fruit, known as the King of Fruits."],
    ["Which is the smallest state in India by area?","Sikkim","Tripura","Goa","Manipur",2,"Goa is the smallest state in India by area."],
    ["What is the national anthem of India?","Vande Mataram","Jana Gana Mana","Saare Jahan Se Achha","Jai Hind",1,"Jana Gana Mana was adopted as the national anthem on January 24, 1950."],
    ["Which mountain range is in the north of India?","Vindhyas","Western Ghats","Himalayas","Aravalli",2,"The Himalayas form the northern boundary of India."]
  ],
  medium:[
    ["What is the capital of Rajasthan?","Jodhpur","Jaipur","Udaipur","Ajmer",1,"Jaipur, the Pink City, is the capital of Rajasthan."],
    ["Which Indian state has the longest coastline?","Maharashtra","Tamil Nadu","Gujarat","Kerala",2,"Gujarat has the longest coastline in India at about 1,600 km."],
    ["What is the highest peak in India?","Mount Everest","K2","Kangchenjunga","Nanda Devi",2,"Kangchenjunga at 8,586 m is the highest peak in India."],
    ["Which city is known as the Silicon Valley of India?","Mumbai","Hyderabad","Bangalore","Pune",2,"Bangalore (Bengaluru) is known as the Silicon Valley of India."],
    ["Which Indian state is known as the Land of Five Rivers?","Haryana","Himachal Pradesh","Punjab","Uttarakhand",2,"Punjab means Land of Five Rivers — Jhelum, Chenab, Ravi, Beas, and Sutlej."],
    ["What is the largest lake in India?","Dal Lake","Vembanad Lake","Chilika Lake","Wular Lake",2,"Chilika Lake in Odisha is the largest coastal lagoon in India."],
    ["Which city is known as the Pink City?","Jodhpur","Jaipur","Jaisalmer","Bikaner",1,"Jaipur is called the Pink City because of its pink-colored buildings."],
    ["What is the capital of Uttarakhand?","Haridwar","Rishikesh","Dehradun","Nainital",2,"Dehradun is the capital of Uttarakhand."],
    ["Which Indian state produces the most tea?","West Bengal","Himachal Pradesh","Assam","Kerala",2,"Assam is the largest tea-producing state in India."],
    ["What is the capital of Telangana?","Warangal","Hyderabad","Nizamabad","Karimnagar",1,"Hyderabad is the capital of Telangana."],
    ["Which is the largest port in India?","Mumbai Port","Chennai Port","Jawaharlal Nehru Port","Kandla Port",2,"Jawaharlal Nehru Port (JNPT) in Mumbai is India's largest container port."],
    ["What is the capital of Sikkim?","Namchi","Pelling","Gangtok","Gyalshing",2,"Gangtok is the capital of Sikkim."],
    ["Which Indian state is known as the Spice Garden of India?","Tamil Nadu","Karnataka","Kerala","Goa",2,"Kerala is known as the Spice Garden of India."],
    ["What is the capital of Arunachal Pradesh?","Tawang","Ziro","Itanagar","Pasighat",2,"Itanagar is the capital of Arunachal Pradesh."],
    ["Which city is known as the City of Lakes?","Jaipur","Jodhpur","Udaipur","Ajmer",2,"Udaipur in Rajasthan is known as the City of Lakes."]
  ],
  hard:[
    ["What is the Panchayati Raj system in India?","A central government system","Three-tier local self-government system at village, block, and district levels","A judicial system","A tax collection system",1,"The Panchayati Raj system was constitutionally established by the 73rd Amendment in 1992."],
    ["Which article of the Indian Constitution abolishes untouchability?","Article 14","Article 15","Article 17","Article 21",2,"Article 17 of the Indian Constitution abolishes untouchability in all forms."],
    ["What is the significance of Article 370?","It defines fundamental rights","It gave special autonomous status to Jammu and Kashmir","It defines directive principles","It establishes the Supreme Court",1,"Article 370 was abrogated in August 2019, removing J&K's special status."],
    ["What is the Goods and Services Tax (GST)?","A direct tax on income","A unified indirect tax system replacing multiple taxes","A property tax","A customs duty",1,"GST was implemented in India on July 1, 2017."],
    ["Which Indian state has the highest literacy rate?","Mizoram","Goa","Kerala","Himachal Pradesh",2,"Kerala has consistently maintained the highest literacy rate in India."],
    ["What is the significance of the 73rd Constitutional Amendment?","It gave voting rights to women","It gave constitutional status to Panchayati Raj institutions","It abolished zamindari","It created new states",1,"The 73rd Amendment of 1992 gave constitutional recognition to Panchayati Raj."],
    ["What is the Pradhan Mantri Jan Dhan Yojana?","A housing scheme","A financial inclusion scheme for opening bank accounts","An employment scheme","An education scheme",1,"PMJDY was launched in 2014 to provide banking access to all households."],
    ["Which Indian city has the highest population density?","Delhi","Kolkata","Mumbai","Chennai",2,"Mumbai has the highest population density among major Indian cities."],
    ["What is the significance of the National Food Security Act?","It promotes agriculture","It provides legal right to subsidized food grains to poor families","It regulates food prices","It controls food imports",1,"The NFSA of 2013 covers about two-thirds of India's population."],
    ["What is the Lokpal?","A state government body","An anti-corruption ombudsman institution at the national level","A judicial court","A police organization",1,"The Lokpal and Lokayuktas Act was passed in 2013 to fight corruption."],
    ["Which Indian state has the most number of districts?","Bihar","Madhya Pradesh","Uttar Pradesh","Maharashtra",2,"Uttar Pradesh has the most districts in India with 75 districts."],
    ["What is the significance of the Right to Information Act?","It gives right to education","It allows citizens to request information from government","It gives right to vote","It gives right to work",1,"The RTI Act of 2005 promotes transparency and accountability in government."],
    ["What is the NITI Aayog?","A judicial body","A policy think tank that replaced the Planning Commission","A military organization","A financial institution",1,"NITI Aayog was established in 2015 replacing the Planning Commission."],
    ["Which Indian state has the lowest population?","Mizoram","Nagaland","Sikkim","Goa",2,"Sikkim is the least populated state in India."],
    ["What is the Aadhaar system?","A passport system","A biometric identification system with a 12-digit unique number","A voter ID system","A ration card system",1,"Aadhaar is issued by UIDAI and is used for identity verification across India."],
    ["Which Indian state has the highest per capita income?","Maharashtra","Delhi","Goa","Karnataka",2,"Goa consistently has the highest per capita income among Indian states."],
    ["What is the significance of the Motor Vehicles Amendment Act 2019?","It reduced traffic fines","It significantly increased penalties for traffic violations","It banned old vehicles","It introduced new vehicle types",1,"The MV Amendment Act 2019 increased fines for drunk driving, speeding, and other violations."],
    ["What is the National Register of Citizens (NRC)?","A voter registration system","A register of Indian citizens used to identify illegal immigrants","A property registration system","A business registration system",1,"The NRC was first implemented in Assam to identify illegal immigrants."],
    ["What is the significance of the Scheduled Castes and Scheduled Tribes Act 1989?","It provides reservations","It prevents atrocities against SC/ST communities","It defines SC/ST categories","It provides financial aid",1,"The SC/ST Prevention of Atrocities Act protects marginalized communities from discrimination."],
    ["What is the Competition Commission of India?","A sports body","A regulatory body that prevents anti-competitive practices","A trade union","A consumer court",1,"The CCI was established under the Competition Act 2002 to promote fair competition."]
  ]
};