/* HTML Basics — 50 Questions */
const T_HTML = {
  name:{en:'HTML Basics',hi:'HTML मूल बातें'}, icon:'🌐',
  easy:[
    ["What does HTML stand for?","HyperText Modern Language","HyperText Markup Language","High Tech Markup Language","HyperTransfer Markup Language",1,"HTML is the standard language for creating web pages."],
    ["Which HTML tag is used for the largest heading?","h6","h1","heading","head",1,"Headings go from h1 (largest) to h6 (smallest)."],
    ["Which HTML tag creates a hyperlink?","link","url","a","href",2,"The anchor tag with href attribute creates hyperlinks."],
    ["Which tag is used for an unordered list?","ol","li","ul","list",2,"UL = Unordered List, OL = Ordered List."],
    ["Which attribute specifies the URL of a hyperlink?","src","link","url","href",3,"href stands for Hypertext Reference."],
    ["Which HTML tag is used to display an image?","picture","img","image","src",1,"The img tag is a self-closing tag used to embed images."],
    ["Which HTML tag creates a line break?","lb","break","br","newline",2,"br stands for break, it is a self-closing tag."],
    ["Which HTML tag makes text bold?","Only bold","Only strong","Only b","Both b and strong",3,"Both b and strong make text bold, but strong has semantic meaning."],
    ["Which HTML tag creates a paragraph?","para","pg","p","paragraph",2,"The p tag defines a paragraph."],
    ["What is the root element of an HTML page?","body","head","html","root",2,"The html element is the root of an HTML document."],
    ["Which HTML tag is used for italic text?","italic","i","em","Both i and em",3,"Both i and em display italic text, but em has semantic emphasis."],
    ["Which HTML tag creates an ordered list?","ul","ol","list","numbered",1,"OL stands for Ordered List, which uses numbers by default."],
    ["Which HTML tag is used for a table row?","td","th","tr","row",2,"tr stands for Table Row."],
    ["Which attribute specifies the source of an image?","href","link","url","src",3,"src stands for source, used in img, script, and iframe tags."],
    ["Which HTML tag creates a form?","input","form","submit","field",1,"The form element is used to create an HTML form for user input."]
  ],
  medium:[
    ["What is the purpose of the DOCTYPE declaration?","To style the page","To tell the browser which HTML version is used","To link CSS files","To define the page title",1,"DOCTYPE html tells the browser to use HTML5."],
    ["Which HTML5 element is used for navigation links?","menu","nav","navigation","links",1,"The nav element defines a set of navigation links."],
    ["Which attribute makes an input field required?","mandatory","required","must","validate",1,"The required attribute prevents form submission if the field is empty."],
    ["Which HTML5 element is used for footer content?","bottom","end","footer","foot",2,"The footer element defines a footer for a document or section."],
    ["What does the alt attribute in the img tag do?","Changes image size","Provides alternative text if image fails to load","Links to another image","Sets image alignment",1,"Alt text is important for accessibility and SEO."],
    ["Which input type creates a checkbox?","type=check","type=box","type=checkbox","type=tick",2,"input type=checkbox creates a checkbox input."],
    ["What is the primary purpose of the meta tag?","To display content","To provide metadata about the HTML document","To create links","To add scripts",1,"Meta tags provide information about the page to browsers and search engines."],
    ["Which HTML element creates a dropdown list?","dropdown","list","select","option",2,"The select element creates a dropdown list with option elements inside."],
    ["Which attribute specifies the character encoding for an HTML document?","encoding","charset","language","type",1,"meta charset=UTF-8 is the most common encoding declaration."],
    ["Which HTML tag is used for a table header cell?","td","tr","th","thead",2,"th stands for Table Header, which is bold and centered by default."],
    ["What is the purpose of the HTML5 canvas element?","To display images","To draw graphics via JavaScript","To create forms","To embed videos",1,"Canvas provides a drawing surface that can be manipulated with JavaScript."],
    ["Which attribute opens a link in a new browser tab?","target=new","target=_blank","target=tab","open=new",1,"target=_blank opens the link in a new tab or window."],
    ["Which HTML tag is used for a definition list?","list","dl","def","description",1,"dl (Definition List) contains dt (term) and dd (description) elements."],
    ["Which HTML5 element represents standalone content that could be distributed independently?","section","div","article","aside",2,"An article could be a blog post, news article, or forum post."],
    ["What is the purpose of the fieldset tag?","To create input fields","To group related form elements","To style form elements","To validate form data",1,"fieldset groups related elements in a form, often with a legend."]
  ],
  hard:[
    ["What is the key difference between section and article in HTML5?","No difference, they are interchangeable","article is for standalone content, section is for thematic grouping","section is for standalone content, article is for thematic grouping","article is deprecated in HTML5",1,"An article should make sense on its own; a section is part of a larger whole."],
    ["What is the purpose of the defer attribute in a script tag?","Loads script asynchronously","Delays script execution until HTML parsing is complete","Prevents script from loading","Loads script from cache",1,"defer ensures scripts execute in order after the DOM is ready."],
    ["What is the difference between async and defer for script loading?","No difference","async executes immediately when downloaded, defer waits for HTML parsing","defer executes immediately, async waits","Both wait for DOM to be ready",1,"async does not guarantee execution order; defer does."],
    ["What is the purpose of the HTML5 template element?","To create page templates","To hold client-side content not rendered until activated by JavaScript","To define CSS templates","To create reusable components",1,"Template content is inert — scripts do not run, images do not load until cloned."],
    ["What is the purpose of the HTML5 picture element?","To display multiple images","To provide responsive image loading with multiple sources","To create image galleries","To replace the img tag",1,"picture allows different images for different screen sizes or resolutions."],
    ["What does the data-* attribute pattern allow in HTML5?","Storing CSS data","Storing custom data private to the page or application","Linking to databases","Defining data types",1,"Custom data attributes can be accessed via JavaScript's dataset property."],
    ["What is the purpose of the contenteditable attribute?","Makes content read-only","Makes an element's content editable by the user","Enables content validation","Locks content from editing",1,"contenteditable=true turns any element into an editable area."],
    ["What is the purpose of the HTML5 output element?","To display server output","To represent the result of a calculation or user action","To show error messages","To display form data",1,"output is typically used with forms to show calculation results."],
    ["What is the purpose of the HTML5 dialog element?","To create chat interfaces","To create dialog boxes or modal windows","To display alerts","To create popup menus",1,"dialog can be shown or hidden with the open attribute or JavaScript methods."],
    ["What is the purpose of the accesskey attribute in HTML?","To set password protection","To specify a keyboard shortcut to activate or focus an element","To control access permissions","To define API keys",1,"accesskey provides keyboard shortcuts for accessibility."],
    ["What is the purpose of the HTML5 details and summary elements?","To create tooltips","To create a disclosure widget where content can be shown or hidden","To add metadata","To create expandable tables",1,"details creates an accordion-like widget; summary is the visible heading."],
    ["What is the purpose of the HTML5 time element?","To display a clock","To represent a specific time or date in a machine-readable format","To create timers","To show timestamps",1,"The datetime attribute provides the machine-readable format."],
    ["What is the difference between id and class attributes in HTML?","No difference","id must be unique per page, class can be used multiple times","class must be unique, id can repeat","id is for CSS only, class is for JavaScript",1,"IDs are unique identifiers; classes can be shared among multiple elements."],
    ["What is the purpose of the HTML5 progress element?","To show loading animations","To represent the completion progress of a task","To display percentage values","To create progress bars in CSS",1,"progress value=70 max=100 shows 70% completion."],
    ["What is the purpose of the role attribute in HTML?","To define user roles","To provide ARIA semantic meaning to elements for accessibility","To set element permissions","To define CSS roles",1,"ARIA roles help screen readers understand the purpose of elements."],
    ["What is the purpose of the HTML5 mark element?","To create bookmarks","To highlight text for reference purposes","To mark errors in text","To create annotations",1,"mark is like a yellow highlighter for web text."],
    ["What is the srcset attribute used for in HTML5?","To set multiple CSS sources","To provide multiple image sources for different screen resolutions","To link multiple scripts","To define fallback sources",1,"srcset works with the sizes attribute for responsive images."],
    ["What is the purpose of the HTML5 meter element?","To measure page performance","To represent a scalar measurement within a known range","To display metrics","To create gauges in CSS",1,"meter is for known ranges like disk usage, unlike progress for tasks."],
    ["What does the novalidate attribute do in an HTML form?","Enables extra validation","Disables browser's built-in form validation","Validates on server only","Removes required attributes",1,"novalidate allows form submission without HTML5 validation."],
    ["What is the purpose of the HTML5 wbr element?","To create word breaks in CSS","To specify where a line break may occur in a long word","To wrap text automatically","To break between words",1,"wbr (Word Break Opportunity) suggests where a word can be broken."]
  ]
};