/* Indian History — 50 Questions */
const T_HISTORY = {
  name:{en:'Indian History',hi:'भारतीय इतिहास'}, icon:'🏛️',
  easy:[
    ["Who is known as the Father of the Nation in India?","Jawaharlal Nehru","Mahatma Gandhi","Subhas Chandra Bose","Sardar Patel",1,"Mahatma Gandhi led India's independence movement through non-violence."],
    ["In which year did India gain independence from British rule?","1945","1946","1947","1948",2,"India became independent on August 15, 1947."],
    ["Who was the first Prime Minister of India?","Jawaharlal Nehru","Sardar Patel","Rajendra Prasad","Lal Bahadur Shastri",0,"Jawaharlal Nehru served as PM from 1947 to 1964."],
    ["What was the name of Gandhi's famous march against the salt tax?","Quit India March","Non-Cooperation March","Dandi March","Swadeshi March",2,"The Dandi March of 1930 covered 240 miles to the sea."],
    ["Who built the Taj Mahal?","Akbar","Shah Jahan","Aurangzeb","Humayun",1,"Shah Jahan built the Taj Mahal in memory of his wife Mumtaz Mahal."],
    ["In which city is the Red Fort located?","Delhi","Agra","Jaipur","Lucknow",0,"The Red Fort in Delhi was the main residence of Mughal emperors."],
    ["Who was the last Mughal Emperor of India?","Akbar","Aurangzeb","Bahadur Shah Zafar","Shah Jahan",2,"Bahadur Shah Zafar was exiled to Burma after the 1857 revolt."],
    ["Who gave the slogan Jai Hind?","Mahatma Gandhi","Subhas Chandra Bose","Bhagat Singh","Jawaharlal Nehru",1,"Subhas Chandra Bose used this slogan for the Indian National Army."],
    ["In which year was the Indian National Congress founded?","1875","1880","1885","1890",2,"The INC was founded in 1885 by A.O. Hume."],
    ["Who was the first President of India?","Dr. Rajendra Prasad","Dr. S. Radhakrishnan","Zakir Husain","V.V. Giri",0,"Dr. Rajendra Prasad served as President from 1950 to 1962."],
    ["Who wrote the Indian national anthem Jana Gana Mana?","Bankim Chandra Chatterjee","Rabindranath Tagore","Sarojini Naidu","Subramania Bharati",1,"Rabindranath Tagore wrote Jana Gana Mana in 1911."],
    ["In which year did the Sepoy Mutiny occur?","1847","1857","1867","1877",1,"The Sepoy Mutiny of 1857 was the first major uprising against British rule."],
    ["Who was known as the Iron Man of India?","Jawaharlal Nehru","Mahatma Gandhi","Sardar Vallabhbhai Patel","Subhas Chandra Bose",2,"Sardar Patel unified 562 princely states into the Indian Union."],
    ["Which Mughal emperor is known for his policy of religious tolerance?","Babur","Humayun","Akbar","Aurangzeb",2,"Akbar's policy of Sulh-i-Kul promoted universal peace and tolerance."],
    ["Who founded the Arya Samaj in 1875?","Ram Mohan Roy","Swami Vivekananda","Dayananda Saraswati","Bal Gangadhar Tilak",2,"Dayananda Saraswati founded Arya Samaj to reform Hinduism."]
  ],
  medium:[
    ["What was the significance of the Quit India Movement of 1942?","It was a peaceful protest only","It demanded immediate end to British rule in India","It was a trade boycott movement","It was a religious movement",1,"Gandhi launched the Quit India Movement on August 8, 1942."],
    ["Who founded the Mughal Empire in India?","Humayun","Babur","Akbar","Timur",1,"Babur founded the Mughal Empire after the First Battle of Panipat in 1526."],
    ["What was the Battle of Plassey (1757) significant for?","It ended Mughal rule","It established British dominance in India","It started the Maratha Empire","It ended the Carnatic Wars",1,"The Battle of Plassey gave the British East India Company control over Bengal."],
    ["Who was Rani Lakshmibai?","A Mughal princess","Queen of Jhansi who fought in the 1857 revolt","A freedom fighter from Bengal","A poet and writer",1,"Rani Lakshmibai of Jhansi is celebrated as a symbol of resistance."],
    ["What was the Rowlatt Act?","A trade regulation act","A law allowing detention without trial","An education reform act","A land revenue act",1,"The Rowlatt Act of 1919 allowed detention without trial, sparking protests."],
    ["Who was the founder of the Maratha Empire?","Peshwa Bajirao","Chhatrapati Shivaji Maharaj","Sambhaji","Balaji Vishwanath",1,"Chhatrapati Shivaji Maharaj founded the Maratha Empire in the 17th century."],
    ["What was the significance of the Partition of Bengal in 1905?","It improved administration","It sparked a strong nationalist movement","It ended the Mughal era","It created Pakistan",1,"The Partition of Bengal by Lord Curzon sparked the Swadeshi Movement."],
    ["Who was Chandragupta Maurya?","A Mughal emperor","Founder of the Maurya Empire","A Gupta king","A Chola ruler",1,"Chandragupta Maurya founded the Maurya Empire around 322 BCE."],
    ["What was the Non-Cooperation Movement?","A military campaign","Gandhi's campaign to boycott British goods and institutions","A religious movement","A trade union movement",1,"The Non-Cooperation Movement of 1920 was Gandhi's first mass movement."],
    ["Who was Tipu Sultan?","A Mughal emperor","Ruler of Mysore who fought against British","A Maratha chief","A Rajput king",1,"Tipu Sultan, the Tiger of Mysore, died fighting the British in 1799."],
    ["What was the significance of the Jallianwala Bagh massacre?","It ended the independence movement","British troops killed hundreds of unarmed civilians","It started the Mughal era","It ended the Maratha Empire",1,"The Jallianwala Bagh massacre of 1919 shocked the nation and world."],
    ["Who was Ashoka the Great?","A Mughal emperor","Mauryan emperor who embraced Buddhism after Kalinga War","A Gupta king","A Chola ruler",1,"Ashoka spread Buddhism across Asia after the bloody Kalinga War."],
    ["What was the Khilafat Movement?","A Hindu religious movement","Muslim movement to protect the Ottoman Caliphate","A trade movement","An education movement",1,"The Khilafat Movement (1919-1924) united Hindus and Muslims against British rule."],
    ["Who was Bal Gangadhar Tilak?","A Mughal noble","Nationalist leader who said Swaraj is my birthright","A British loyalist","A religious reformer",1,"Tilak's slogan was Swaraj is my birthright and I shall have it."],
    ["What was the significance of the Cabinet Mission Plan of 1946?","It ended World War II","It proposed a framework for Indian independence","It created Pakistan","It ended the Mughal Empire",1,"The Cabinet Mission Plan proposed a united India with a federal structure."]
  ],
  hard:[
    ["What was the Doctrine of Lapse introduced by Lord Dalhousie?","A tax policy","Policy annexing states without a male heir to the British Empire","A military strategy","An education policy",1,"The Doctrine of Lapse was used to annex Satara, Jhansi, and Nagpur."],
    ["What was the significance of the Third Battle of Panipat (1761)?","Mughal victory over Marathas","Maratha defeat by Ahmad Shah Durrani of Afghanistan","British victory over Marathas","Maratha victory over Mughals",1,"The Third Battle of Panipat ended Maratha expansion northward."],
    ["Who was Akbar's finance minister known for land revenue reforms?","Birbal","Todar Mal","Abul Fazl","Bairam Khan",1,"Todar Mal introduced the Zabti system of land revenue measurement."],
    ["What was the Permanent Settlement of 1793?","A peace treaty","Fixed land revenue system in Bengal introduced by Cornwallis","A military agreement","An education policy",1,"The Permanent Settlement fixed zamindars as permanent owners of land."],
    ["What was the significance of the Ilbert Bill controversy (1883)?","It gave Indians voting rights","It proposed allowing Indian judges to try Europeans","It ended zamindari system","It created Indian Civil Service",1,"The Ilbert Bill controversy revealed racial prejudice in British India."],
    ["Who was Lala Lajpat Rai?","A Mughal noble","Nationalist leader who died after police lathi charge","A British loyalist","A religious reformer",1,"Lala Lajpat Rai died in 1928 after being beaten during anti-Simon Commission protests."],
    ["What was the Poona Pact of 1932?","A military agreement","Agreement between Gandhi and Ambedkar on reserved seats for Dalits","A trade agreement","A religious agreement",1,"The Poona Pact ended Gandhi's fast-unto-death and secured Dalit representation."],
    ["What was the significance of the Chauri Chaura incident?","It started the independence movement","Gandhi suspended the Non-Cooperation Movement after violence","It ended British rule","It started the Quit India Movement",1,"Gandhi suspended the Non-Cooperation Movement in 1922 after the Chauri Chaura violence."],
    ["Who was Bhagat Singh?","A Mughal noble","Revolutionary who was hanged for killing British officer Saunders","A Congress leader","A religious reformer",1,"Bhagat Singh was hanged in 1931 at age 23 and became a revolutionary icon."],
    ["What were the Morley-Minto Reforms of 1909?","Education reforms","Reforms that introduced separate electorates for Muslims in India","Military reforms","Land revenue reforms",1,"The Morley-Minto Reforms introduced communal representation, dividing Hindus and Muslims."],
    ["What was the significance of the Dandi March?","It ended British rule","It broke the salt law and sparked the Civil Disobedience Movement","It started the Quit India Movement","It created the Indian National Congress",1,"The Dandi March of 1930 was a pivotal act of civil disobedience."],
    ["What was Subhas Chandra Bose's role in Indian independence?","He was a Congress president only","He led the Indian National Army against British forces","He negotiated with British","He wrote the Constitution",1,"Bose formed the INA with the slogan Give me blood and I will give you freedom."],
    ["What was the Lucknow Pact of 1916?","A military agreement","Congress-Muslim League agreement on separate electorates","A trade agreement","A religious agreement",1,"The Lucknow Pact brought Congress and Muslim League together temporarily."],
    ["Who was Dadabhai Naoroji?","A Mughal noble","First Indian elected to British Parliament, known for drain theory","A religious reformer","A military leader",1,"Dadabhai Naoroji's drain theory argued British rule was economically exploiting India."],
    ["What was the Swadeshi Movement?","A religious movement","Boycott of British goods and promotion of Indian products","A military movement","An education movement",1,"The Swadeshi Movement of 1905 promoted Indian-made goods and boycotted British products."],
    ["What was the significance of the Montagu-Chelmsford Reforms?","They gave India independence","They introduced dyarchy in Indian provinces","They ended zamindari","They created the Indian Army",1,"The Montagu-Chelmsford Reforms of 1919 introduced dyarchy in provincial governments."],
    ["Who was Gopal Krishna Gokhale?","A Mughal noble","Moderate nationalist leader and mentor of Mahatma Gandhi","A British loyalist","A military leader",1,"Gokhale founded the Servants of India Society and was Gandhi's political mentor."],
    ["What was the significance of the Cripps Mission?","It gave India independence","It was a failed attempt to gain Indian support in World War II","It ended the Mughal Empire","It created Pakistan",1,"The Cripps Mission of 1942 failed as Congress rejected its proposals."],
    ["What was the role of the Indian National Army (INA)?","A British army unit","Armed force led by Bose to fight British and liberate India","A police force","A trade organization",1,"The INA fought alongside Japanese forces in Southeast Asia during World War II."],
    ["What was the significance of the Wavell Plan of 1945?","It gave India independence","It proposed an interim government with Indian leaders","It created Pakistan","It ended World War II",1,"The Wavell Plan failed due to disagreements between Congress and Muslim League."]
  ]
};