/* Super Basics — 50 Questions (99%+ people know these!) */
const T_BASICS = {
  name:{en:'Super Basics',hi:'सुपर बेसिक्स'}, icon:'⭐',
  easy:[
    ["How many days are in a week?","5","6","8","7",3,"There are 7 days in a week: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday."],
    ["What color is the sky on a clear day?","Green","Red","Blue","Yellow",2,"The sky appears blue because of a phenomenon called Rayleigh scattering of sunlight."],
    ["How many months are in a year?","10","11","13","12",3,"There are 12 months in a year, from January to December."],
    ["What is 2 + 2?","3","5","4","6",2,"2 + 2 = 4. This is one of the most basic arithmetic facts."],
    ["Which planet do we live on?","Mars","Venus","Jupiter","Earth",3,"We live on Earth, the third planet from the Sun in our solar system."],
    ["How many fingers are on ONE hand?","4","6","3","5",3,"Each human hand has 5 fingers: thumb, index, middle, ring, and little finger."],
    ["What is the opposite of HOT?","Warm","Cool","Cold","Dry",2,"The opposite of hot is cold. These are antonyms describing temperature extremes."],
    ["Which animal says 'meow'?","Dog","Cow","Cat","Horse",2,"Cats make the 'meow' sound. Dogs bark, cows moo, and horses neigh."],
    ["How many hours are in a day?","12","48","36","24",3,"There are 24 hours in a day — 12 hours AM and 12 hours PM."],
    ["What comes after MONDAY?","Sunday","Wednesday","Thursday","Tuesday",3,"The days of the week in order are: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday."],
    ["What color is grass?","Yellow","Blue","Green","Brown",2,"Grass is green because it contains chlorophyll, a green pigment used in photosynthesis."],
    ["How many legs does a dog have?","2","6","3","4",3,"Dogs are quadrupeds — they have 4 legs. Most mammals have 4 legs."],
    ["How many seconds are in ONE minute?","100","30","120","60",3,"There are 60 seconds in one minute, and 60 minutes in one hour."],
    ["What do we use to write on paper?","Brush","Spoon","Pen or Pencil","Fork",2,"We use a pen or pencil to write on paper. Pens use ink, pencils use graphite."],
    ["What is the color of the sun?","Blue","White/Yellow","Red","Green",1,"The sun appears yellow or white. It is actually a white star, but appears yellow from Earth's surface."]
  ],
  medium:[
    ["How many continents are there on Earth?","5","6","8","7",3,"There are 7 continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia."],
    ["What is the largest ocean on Earth?","Atlantic Ocean","Indian Ocean","Arctic Ocean","Pacific Ocean",3,"The Pacific Ocean is the largest and deepest ocean, covering more than 30% of Earth's surface."],
    ["Which is the tallest mountain in the world?","K2","Kangchenjunga","Mount Everest","Lhotse",2,"Mount Everest at 8,848.86 meters is the tallest mountain above sea level."],
    ["How many colors are in a rainbow?","5","6","8","7",3,"A rainbow has 7 colors: Red, Orange, Yellow, Green, Blue, Indigo, Violet (ROYGBIV)."],
    ["What is H2O?","Salt","Oxygen","Carbon Dioxide","Water",3,"H2O is the chemical formula for water — 2 hydrogen atoms bonded to 1 oxygen atom."],
    ["How many bones are in the adult human body?","300","150","250","206",3,"An adult human body has 206 bones. Babies are born with about 270-300 bones that fuse over time."],
    ["What is the capital of France?","London","Berlin","Rome","Paris",3,"Paris is the capital and largest city of France, known as the 'City of Light'."],
    ["Which is the largest planet in our solar system?","Saturn","Neptune","Uranus","Jupiter",3,"Jupiter is the largest planet in our solar system — it's so big that all other planets could fit inside it."],
    ["How many sides does a triangle have?","4","2","5","3",3,"A triangle has 3 sides and 3 angles. 'Tri' means three in Latin."],
    ["What do plants need to make food (photosynthesis)?","Moonlight","Darkness","Sunlight","Rain only",2,"Plants use sunlight, water, and carbon dioxide to make food through photosynthesis."],
    ["What is the boiling point of water?","50°C","75°C","100°C","150°C",2,"Water boils at 100°C (212°F) at standard atmospheric pressure."],
    ["How many players are in a cricket team?","9","10","12","11",3,"A cricket team has 11 players. The batting side sends 2 players at a time to bat."],
    ["What is the freezing point of water?","-10°C","10°C","0°C","5°C",2,"Water freezes at 0°C (32°F) at standard atmospheric pressure."],
    ["Which gas do humans breathe in?","Carbon Dioxide","Nitrogen","Hydrogen","Oxygen",3,"Humans breathe in oxygen (O2) and breathe out carbon dioxide (CO2)."],
    ["How many zeros are in ONE MILLION?","4","5","7","6",3,"One million = 1,000,000 — it has 6 zeros."]
  ],
  hard:[
    ["What is the chemical symbol for GOLD?","Go","Gd","Gl","Au",3,"Gold's symbol is Au, from the Latin word 'Aurum'. It's a precious yellow metal."],
    ["Who invented the telephone?","Thomas Edison","Nikola Tesla","Alexander Graham Bell","James Watt",2,"Alexander Graham Bell is credited with inventing the telephone in 1876."],
    ["What is the square root of 144?","11","13","14","12",3,"√144 = 12, because 12 × 12 = 144."],
    ["Which gas do plants absorb from the air?","Oxygen","Nitrogen","Hydrogen","Carbon Dioxide",3,"Plants absorb carbon dioxide (CO2) from the air and release oxygen during photosynthesis."],
    ["What is the largest country in the world by area?","Canada","China","USA","Russia",3,"Russia is the largest country by area at about 17.1 million square kilometers."],
    ["How many planets are in our solar system?","7","9","10","8",3,"There are 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. Pluto was reclassified in 2006."],
    ["What is the speed of light (approximately)?","3 × 10⁸ m/s","3 × 10⁶ m/s","3 × 10⁴ m/s","3 × 10¹⁰ m/s",0,"The speed of light in vacuum is approximately 3 × 10⁸ meters per second (300,000 km/s)."],
    ["Who painted the Mona Lisa?","Michelangelo","Raphael","Pablo Picasso","Leonardo da Vinci",3,"The Mona Lisa was painted by Leonardo da Vinci between 1503 and 1519."],
    ["What is the chemical symbol for water?","HO","H2O2","H3O","H2O",1,"Water's chemical formula is H2O — 2 hydrogen atoms bonded to 1 oxygen atom."],
    ["Which is the smallest planet in our solar system?","Mars","Venus","Pluto","Mercury",3,"Mercury is the smallest planet in our solar system and also the closest to the Sun."],
    ["What is the powerhouse of the cell?","Nucleus","Ribosome","Golgi Body","Mitochondria",3,"Mitochondria are called the powerhouse of the cell because they produce ATP (energy) through cellular respiration."],
    ["How many sides does a hexagon have?","5","7","8","6",3,"A hexagon has 6 sides. 'Hex' means six in Greek. Honeycombs are hexagonal."],
    ["What is the full form of DNA?","Deoxyribonucleic Acid","Deoxyribose Nucleic Acid","Deoxyribonuclear Acid","Deoxyribonucleic Amino",0,"DNA stands for Deoxyribonucleic Acid — it carries genetic information in living organisms."],
    ["Who wrote Romeo and Juliet?","Charles Dickens","Jane Austen","Mark Twain","William Shakespeare",3,"Romeo and Juliet was written by William Shakespeare around 1594-1596."],
    ["What is the hardest natural substance on Earth?","Gold","Iron","Quartz","Diamond",3,"Diamond is the hardest natural substance on Earth, rating 10 on the Mohs hardness scale."],
    ["How many teeth does a healthy adult human have?","28","30","36","32",3,"A healthy adult human has 32 teeth, including 4 wisdom teeth."],
    ["What is the currency of Japan?","Won","Yuan","Ringgit","Yen",3,"The Japanese Yen (¥) is the official currency of Japan."],
    ["Which organ pumps blood in the human body?","Liver","Lungs","Kidney","Heart",3,"The heart is a muscular organ that pumps blood throughout the body via the circulatory system."],
    ["What is the largest desert in the world?","Gobi Desert","Sahara Desert","Arabian Desert","Antarctic Desert",3,"The Antarctic Desert is the largest desert at 14.2 million km². The Sahara is the largest HOT desert."],
    ["What does 'E=mc²' represent?","Electrical energy formula","Einstein's theory of relativity — energy equals mass times speed of light squared","Euler's mathematical constant","Electromagnetic constant",1,"E=mc² is Einstein's famous equation showing that energy (E) equals mass (m) times the speed of light (c) squared."]
  ]
};